blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='home'),
    path('home/', views.index, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('posts/create/', views.create_post, name="create_post"),
    path('posts/publish/', views.publish_new_post, name='publish_new_post'),
    path('posts/<int:pk>/edit/', views.edit_post, name="edit_post"),
    path('posts/<int:pk>/publish/', views.publish_post, name="publish_post"),
    path('posts/<int:pk>/delete/', views.delete_post, name="delete_post"),
    path('posts/<int:pk>/view/', views.view_post, name="view_post"),
    path('posts/<int:pk>/like/', views.like_post, name="like_post"),
    path('posts/<int:pk>/unlike/', views.unlike_post, name="unlike_post"),
    path('posts/<int:pk>/comment/', views.comment_post, name="comment_post"),
    path('posts/<int:pk>/share/', views.share_post, name="share_post"),
    path('comment/<int:pk>/reply/', views.reply_comment, name='reply_comment'),
    path('account/posts/', views.my_posts, name='my_posts'),
    path('users/<str:username>/follow/', views.follow_user,
         name='follow_user'),
    path('users/<str:username>/unfollow/', views.unfollow_user,
         name='unfollow_user'),
    path('users/<str:username>/', views.view_user, name='view_user'),
    path('users/', views.users, name='users'),
    path('locations/<int:pk>/', views.view_location, name='view_location'),
    path('locations/<int:pk>/follow/', views.follow_location,
         name='follow_location'),
    path('locations/<int:pk>/unfollow/', views.unfollow_location,
         name='unfollow_location'),
    path('tags/<int:pk>/', views.view_tag, name='view_tag'),
    path('explore/', views.explore, name='explore'),
]

travelcave/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blog/models.py
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


def profile_image(instance, filename):
    """
    This function generates the path where a profile image should be saved to.

    :param instance: Instance of User Profile to be saved
    :param filename: Name of file to be uploaded
    :return: Path of file
    """
    ext = filename.split('.')[-1]
    return 'image/user_{0}.{1}'.format(instance.user.id, ext)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField()
    twitter = models.CharField(max_length=50, null=True, blank=True)
    instagram = models.CharField(max_length=50, null=True, blank=True)
    facebook = models.CharField(max_length=50, null=True, blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    users_following = models.ManyToManyField(to='self', symmetrical=False,
                                             related_name='followers',
                                             blank=True)
    locations_following = models.ManyToManyField(to='Location', blank=True,
                                                 related_name='followers')
    liked_posts = models.ManyToManyField(to='Post', through='PostLike',
                                         related_name='users_liked',
                                         blank=True)
    image = models.ImageField(null=True, blank=True, upload_to=profile_image)

    def __str__(self):
        """
        Profile model as String.

        :return: self.user.username
        """
        return self.user.username


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        """
        Tag model as String.

        :return: self.name
        """
        return self.name


class Location(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        """
        Location model as String.

        :return: self.name
        """
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    slug = AutoSlugField(populate_from='title')
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE,
                               blank=True, related_name='blog_posts')
    locations = models.ManyToManyField(to=Location, related_name='reviews',
                                       through='LocationReview')
    tags = models.ManyToManyField(to=Tag, related_name='blog_posts')
    total_likes = models.IntegerField(default=0)
    total_comments = models.IntegerField(default=0)
    total_shares = models.IntegerField(default=0)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        """
        Post model as String.

        :return: self.title by self.author
        """
        return f'{self.title} by {str(self.author)}'

    def get_absolute_url(self):
        """
        Post model url
        :return: absolute url of the post
        """
        return reverse('blog:view_post', kwargs={'pk': self.pk})


class PostLike(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.DO_NOTHING)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        """
        Meta options for PostLike model
        """
        ordering = ['-created_at']

    def __str__(self):
        """
        PostLike model as String.

        :return: self.user liked self.post on self.created_at
        """
        return f'{str(self.user)} liked {str(self.post)} on {self.created_at}'


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.DO_NOTHING)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent = models.ForeignKey('Comment', on_delete=models.DO_NOTHING,
                               null=True, blank=True, related_name='replies')
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        """
        Meta options for Comment Model
        """
        ordering = ['-created_at']

    def __str__(self):
        """
        Comment model as String.

        :return: self.user commented on self.post on self.created_at
        """
        return f'{str(self.user)} commented on {str(self.post)} on {self.created_at}'


class LocationReview(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    sentiment = models.FloatField()
    magnitude = models.FloatField()

    def __str__(self):
        """
        LocationReview model as String.

        :return: self.location in self.post
        """
        return f'{str(self.location)} in {str(self.post)}'

blog/forms.py
from django import forms
from django_summernote.widgets import SummernoteInplaceWidget

from blog.models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=SummernoteInplaceWidget())

    class Meta:
        """
        Meta options for Post Form
        """
        model = Post
        exclude = ('slug', 'author', 'is_published', 'locations', 'tags',
                   'total_comments', 'total_likes', 'total_shares')

blog/views.py
from datetime import timedelta, datetime
from itertools import chain
from operator import attrgetter

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.postgres.search import SearchVector, SearchRank
from django.db.models import Count, Avg
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.dateparse import parse_datetime
from django.utils.timezone import now
from google.cloud import language_v1beta2 as language
from google.cloud.language_v1beta2 import Entity, EntityMention, Document

from blog.forms import PostForm
from blog.models import Profile, Post, Location, LocationReview, Tag, \
    PostLike, Comment


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            last_login = user.last_login
            login(request, user)
            if last_login is not None:
                request.session['previous_login'] = last_login.isoformat()
            return redirect('blog:home')
        else:
            # Return an 'invalid login' error message.
            ...
    elif request.method == 'GET':
        return render(request, 'login.html')


def index(request):
    recent_posts = Post.objects.filter(is_published=True)[:12]
    today = datetime.now()
    week_ago = today - timedelta(days=7)
    trending_locations = Location.objects.filter(
        reviews__postlike__created_at__gte=week_ago).annotate(
        likes_count=Count('reviews__postlike', distinct=True),
        average_sentiment=Avg('locationreview__sentiment',
                              distinct=True)).order_by('-likes_count')[:12]
    return render(request, 'index.html', {'recent_posts': recent_posts,
                                          'trending_locations': trending_locations})


def view_post(request, pk):
    post = Post.objects.get(id=pk)
    profile = post.author
    return render(request, 'view_post.html',
                  {'post': post, 'profile': profile})


@login_required
def publish_new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user.profile
            instance.is_published = True
            instance.save()
            post = Post.objects.get(id=instance.id)
            analyse_entity_sentiment(form, post)
            classify_post(form, post)
            return redirect('blog:view_post', post.id)
        else:
            return HttpResponse(status=400)


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user.profile
            instance.save()
            post = Post.objects.get(id=instance.id)
            analyse_entity_sentiment(form, post)
            classify_post(form, post)
            return redirect('blog:view_post', post.id)
        else:
            return HttpResponse(status=400)
    elif request.method == 'GET':
        form = PostForm()
        return render(request, 'create_post.html', {'form': form})


def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    elif request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        username = request.POST['username']
        image = request.FILES['image']

        user = User.objects.create_user(username=username, email=email,
                                        password=password,
                                        first_name=first_name,
                                        last_name=last_name)
        user.save()

        user_profile = Profile.objects.create(user=user, image=image)
        user_profile.save()

        return redirect('blog:home')


def logout_view(request):
    logout(request)
    return redirect('blog:home')


@login_required
def my_posts(request):
    posts = request.user.profile.blog_posts.all()
    return render(request, 'posts.html', {'posts': posts})


@login_required
def publish_post(request, pk):
    post = Post.objects.get(id=pk)
    post.is_published = True
    post.save()
    return redirect('blog:view_post', pk)


@login_required
def edit_post(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(id=pk)
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            analyse_entity_sentiment(form, post)
            classify_post(form, post)
            instance = form.save(commit=False)
            instance.author = request.user.profile
            instance.save()
            return redirect('blog:home')
        else:
            return HttpResponse(status=400)
    elif request.method == 'GET':
        post = Post.objects.get(id=pk)
        form = PostForm(instance=post)
    return render(request, 'edit_post.html', {'form': form})


def analyse_entity_sentiment(form, post):
    client, document = extract_document(form)
    response = client.analyze_entity_sentiment(document=document)
    for entity in response.entities:
        if Entity.Type(entity.type).name == 'LOCATION':
            for mention in entity.mentions:
                if EntityMention.Type(
                        mention.type).name == 'PROPER':
                    print(f'\nDetected Location: {entity.name}')
                    print(f'Salience score: {entity.salience}')
                    sentiment = entity.sentiment
                    print(f'Entity sentiment score: {sentiment.score}')
                    print(
                        f'Entity sentiment magnitude: {sentiment.magnitude}')
                    location, created = Location.objects.get_or_create(
                        name=entity.name.lower())
                    location.save()
                    review, created = LocationReview.objects.update_or_create(
                        post=post, location=location,
                        defaults={'sentiment': sentiment.score,
                                  'magnitude': sentiment.magnitude})
                    review.save()


def classify_post(form, post):
    client, document = extract_document(form)
    tags = list()
    try:
        response = client.classify_text(document=document)
        categories = response.categories

        for category in categories:
            tag = category.name.split('/')[-1]
            tag, created = Tag.objects.get_or_create(name=tag)
            tag.save()
            tags.append(tag)
    finally:
        post.tags.set(tags)


def extract_document(form):
    client = language.LanguageServiceClient()
    title = form.cleaned_data.get('title')
    content = form.cleaned_data.get('content')
    text = f"<p>{title}</p>{content}"
    print(text)
    document = Document(content=text, type=Document.Type.HTML)
    return client, document


@login_required
def delete_post(request, pk):
    post = Post.objects.get(id=pk)
    post.delete()
    return redirect('blog:my_posts')


def view_user(request, username):
    profile = Profile.objects.get(user__username=username)
    activities = get_user_activities_sorted(username)
    newsfeed = get_newsfeed_sorted(
        profile.users_following.all()) if request.user.username == username else []
    blog_posts = Post.objects.filter(author=profile)
    reviews = LocationReview.objects.filter(post__in=blog_posts)
    highlight = Post.objects.filter(is_published=True).order_by('-created_at',
                                                                '-total_likes',
                                                                '-total_comments',
                                                                '-total_shares').first()
    # recommend users who follow the same content
    recommended_users = (Profile.objects.filter(
        users_following__in=profile.users_following.all()) | Profile.objects.filter(
        locations_following__in=profile.locations_following.all())).exclude(
        user=request.user).distinct().order_by('?')[:5]
    previous_login = parse_datetime(
        request.session.get('previous_login', now().isoformat()))
    updates = LocationReview.objects.filter(
        location__in=profile.locations_following.all(),
        post__is_published=True,
        post__created_at__gt=previous_login).values('location').annotate(
        total=Count('location')).order_by('total')
    return render(request, 'user.html',
                  {'profile': profile, 'activities': activities,
                   'reviews': reviews, 'highlight': highlight,
                   'recommended_users': recommended_users, 'updates':
                       updates, 'newsfeed': newsfeed})


def get_user_activities_sorted(username):
    user = Profile.objects.get(user__username=username)
    likes = PostLike.objects.filter(user=user)
    comments = Comment.objects.filter(user=user)
    posts = Post.objects.filter(author=user)
    result_list = sorted(chain(likes, comments, posts),
                         key=attrgetter('created_at'), reverse=True)
    return result_list


def get_newsfeed_sorted(users_following):
    likes = PostLike.objects.filter(user__in=users_following)
    comments = Comment.objects.filter(user__in=users_following)
    posts = Post.objects.filter(author__in=users_following)
    result_list = sorted(chain(likes, comments, posts),
                         key=attrgetter('created_at'), reverse=True)
    return result_list


@login_required
def follow_user(request, username):

blog/templates/explore.html
{% extends 'extended_nav.html' %}
{% load static %}
{% block title %}
    Explore
{% endblock %}
{% block styles %}
    <link href="{% static 'css/cards.css' %}" rel="stylesheet"
          type="text/css">
{% endblock %}
{% block breadcrumbs %}
    <a href="{% url 'blog:home' %}" class="breadcrumb">Home</a>
    <a href="#" class="breadcrumb"> Explore</a>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col s12 container">
            <div class="card-panel pb-0">
                <div class="row">
                    <div class="col s12">
                        <form method="get" action="{% url 'blog:explore' %}">
                            <div class="input-field col s10">
                                <i class="material-icons prefix">search</i>
                                <input type="text" name="query" id="query"
                                       value="{{ request.GET.query }}">
                                <label for="query">Explore Travel Cave</label>
                            </div>
                            <div class="input-field col s2">
                                <button class="btn waves-effect waves-light"
                                        type="submit">
                                    <i class="material-icons
                                    right">arrow_right_alt</i>
                                    Search
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="col s12 container">
                        <ul class="tabs tabs-fixed-width">
                            <li class="tab active"><a href="#users">Users</a>
                            </li>
                            <li class="tab"><a href="#posts">Blog Posts</a>
                            </li>
                            <li class="tab"><a href="#tags">Tags</a></li>
                            <li class="tab"><a href="#locations">Locations</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!--Users-->
        <div class="col s12 container" id="users">
            <div class="row">
                {% for profile in profiles %}
                    <div class="card-panel">
                        <div class="row">
                            <div class="col s12 m7">
                                <div class="display-flex media">
                                    <a href="{% url 'blog:view_user' profile.user.username %}"
                                       class="avatar">
                                        <img src="{{ profile.image.url }}"
                                             alt="{{ profile.user.get_full_name }}"
                                             class="z-depth-4 circle"
                                             height="64"
                                             width="64">
                                    </a>
                                    <div class="media-body">
                                        <h6 class="media-heading">
                                    <span class="users-view-name">
                                        {{ profile.user.get_full_name }}
                                    </span>
                                            <span class="grey-text">@</span>
                                            <span class="users-view-username grey-text">{{ profile.user.username }}</span>
                                        </h6>
                                    </div>
                                </div>
                            </div>
                            <div class="col s12 m5 quick-action-btns display-flex justify-content-end align-items-center pt-2">
                                <a href="{% url 'blog:view_user' profile.user.username %}"
                                   class="btn-small">Profile</a>
                                {% if profile in user.profile.users_following.all %}
                                    <a href="{% url 'blog:unfollow_user' profile.user.username %}"
                                       class="btn-small">Unfollow</a>
                                {% else %}
                                    <a href="{% url 'blog:follow_user' profile.user.username %}"
                                       class="btn-small">Follow</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <!--Posts-->
        <div class="col s12 container" id="posts">
            <div class="row">
                <div class="col s12 cards-container">
                    {% for post in posts %}
                        <div class="card-panel border-radius-6 mt-10 card-animation-1">
                            <a href="{% url 'blog:view_post' post.id %}">
                                <img class="responsive-img border-radius-8 z-depth-4 image-n-margin"
                                     src="{% static 'img/sample-1.jpg' %}"
                                     alt=""></a>
                            <h6 class="t-5">
                                <b><a class="text-uppercase"
                                      href="{% url 'blog:view_post' post.id %}">{{ post.title }}</a></b>
                            </h6>
                            <span>{{ post.content|safe|truncatewords_html:25 }}</span>
                            <div class="display-flex justify-content-between flex-wrap mt-4">
                                <div class="display-flex align-items-center mt-1">
                                    <img src="{{ post.author.image.url }}"
                                         class="circle responsive-img
                                             responsive-img-tiny">
                                    <span class="pt-2">
                                            {{ post.author.user.username }}</span>
                                </div>
                                <div class="display-flex mt-3 right-align social-icon">
                                    <span class="material-icons">favorite_border</span>
                                    <span class="ml-3 vertical-align-top">{{ post.total_likes }}</span>
                                    <span class="material-icons ml-10">chat_bubble_outline</span>
                                    <span class="ml-3 vertical-align-top">{{ post.total_comments }}</span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!--Tags-->
        <div class="col s12 container" id="tags">
            <div class="row">
                {% for tag in tags %}
                    <a href="{% url 'blog:view_tag' tag.id %}">
                        <div class="card-panel">
                            <div>
                                <h5 class="pink-text darken-2 text-uppercase">{{ tag }}</h5>
                            </div>
                            <div class="row">
                                {% for post in tag.blog_posts.all|slice:4 %}
                                    {% if post.is_published %}
                                        <div class="col s12 m3">
                                            <div class="card-panel border-radius-6 mt-10 card-animation-1">
                                                <a href="{% url 'blog:view_post' post.id %}">
                                                    <img class="responsive-img border-radius-8 z-depth-4 image-n-margin"
                                                         src="{% static 'img/sample-1.jpg' %}"
                                                         alt=""></a>
                                                <h6 class="t-5">
                                                    <b><a class="text-uppercase"
                                                          href="{% url 'blog:view_post' post.id %}">{{ post.title }}</a></b>
                                                </h6>
                                                <span>{{ post.content|safe|truncatewords_html:25 }}</span>
                                                <div class="display-flex justify-content-between flex-wrap mt-4">
                                                    <div class="display-flex align-items-center mt-1">
                                                        <img src="{{ post.author.image.url }}"
                                                             class="circle responsive-img
                                             responsive-img-tiny">
                                                        <span class="pt-2">
                                            {{ post.author.user.username }}</span>
                                                    </div>
                                                    <div class="display-flex mt-3 right-align social-icon">
                                                        <span class="material-icons">favorite_border</span>
                                                        <span class="ml-3 vertical-align-top">{{ post.total_likes }}</span>
                                                        <span class="material-icons ml-10">chat_bubble_outline</span>
                                                        <span class="ml-3 vertical-align-top">{{ post.total_comments }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
        <!--Locations-->
        <div class="col s12 container" id="locations">
            <div class="row">
                {% for location in locations %}
                    <a href="{% url 'blog:view_location' location.id %}">
                        <div class="card-panel">
                            <div>
                                <h5 class="pink-text darken-2 text-uppercase">{{ location }}</h5>
                            </div>
                            <div class="row">
                                {% for review in location.locationreview_set.all|slice:4 %}
                                    {% if review.post.is_published %}
                                        <div class="col s12 m3">
                                            <div class="card-panel border-radius-6 mt-10 card-animation-1">
                                                <a href="{% url 'blog:view_post' review.post.id %}">
                                                    <img class="responsive-img border-radius-8 z-depth-4 image-n-margin"
                                                         src="{% static 'img/sample-1.jpg' %}"
                                                         alt=""></a>
                                                <h6 class="t-5">
                                                    <b><a class="text-uppercase"
                                                          href="{% url 'blog:view_post' review.post.id %}">{{ review.post.title }}</a></b>
                                                </h6>
                                                <span>{{ review.post.content|safe|truncatewords_html:25 }}</span>
                                                <div class="display-flex justify-content-between flex-wrap mt-4">
                                                    <div class="display-flex align-items-center mt-1">
                                                        <img src="{{ review.post.author.image.url }}"
                                                             class="circle responsive-img
                                             responsive-img-tiny">
                                                        <span class="pt-2">
                                            {{ review.post.author.user.username }}</span>
                                                    </div>
                                                    <div class="display-flex mt-3 right-align social-icon">
                                                        <span class="material-icons">favorite_border</span>
                                                        <span class="ml-3 vertical-align-top">{{ review.post.total_likes }}</span>
                                                        <span class="material-icons ml-10">chat_bubble_outline</span>
                                                        <span class="ml-3 vertical-align-top">{{ review.post.total_comments }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        const elems = document.querySelectorAll('.tabs');
        const options = {}
        var instance = M.Tabs.init(elems, options);
    </script>
{% endblock %}